spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbproducto
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql   
    show-sql: true
  jackson:
    serialization:
      indent-output: true